name: 4-Hour Data Refresh

on:
  schedule:
    # Runs every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  run-daily-refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r dashboard/requirements.txt || pip install -r requirements.txt

      - name: Set up credentials
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          mkdir -p config
          echo "$CREDENTIALS_JSON" > config/credentials.json

      - name: Run refresh script
        run: |
          python dashboard/refresh_app_daily.py

      - name: Commit and push changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-refresh data [skip ci]" || echo "No changes to commit"
          git push