name: 4-Hour Data Refresh

on:
  schedule:
    # Run every 4 hours
    - cron: "0 */4 * * *"
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-refresh:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Set up credentials from GitHub Secrets
      - name: Setup credentials
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          mkdir -p Training_Intensity_Report/config
          echo "$CREDENTIALS_JSON" > Training_Intensity_Report/config/credentials.json


      # 5️⃣ Verify CSV/JSON files exist (optional but helps debug)
      - name: List data files
        run: |
          ls -R

      # 6️⃣ Run the Python script
      - name: Run refresh script
        run: python Training_Intensity_Report/dashboard/refresh_app_daily.py

